-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customers
(
    "CustomerID" numeric,
    "FirstName" text COLLATE pg_catalog."default",
    "LastName" text COLLATE pg_catalog."default",
    "CustomerEmail" text COLLATE pg_catalog."default",
    "CustomerPhone" text COLLATE pg_catalog."default",
    "CustomerAddress" text COLLATE pg_catalog."default",
    "CustomerCity" text COLLATE pg_catalog."default",
    "CustomerState" text COLLATE pg_catalog."default",
    "CustomerZip" numeric,
    CONSTRAINT "CustomerID" PRIMARY KEY ("CustomerID")
);

CREATE TABLE IF NOT EXISTS public.orders
(
    "OrderID" numeric,
    "Date" date,
    "CustomerID" numeric,
    "ProdNumber" text COLLATE pg_catalog."default",
    "Quantity" numeric,
    CONSTRAINT "OrderID" PRIMARY KEY ("OrderID")
);

CREATE TABLE IF NOT EXISTS public.productcategory
(
    "CategoryID" numeric,
    "CategoryName" text COLLATE pg_catalog."default",
    "CategoryAbbreviation" text COLLATE pg_catalog."default",
    CONSTRAINT "CategoryID" PRIMARY KEY ("CategoryID")
);

CREATE TABLE IF NOT EXISTS public.products
(
    "ProdNumber" text COLLATE pg_catalog."default",
    "ProdName" text COLLATE pg_catalog."default",
    "Category" numeric,
    "Price" numeric,
    CONSTRAINT "ProdNumber" PRIMARY KEY ("ProdNumber")
);

ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT "CustomerID" FOREIGN KEY ("CustomerID")
    REFERENCES public.customers ("CustomerID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT "ProdNumber" FOREIGN KEY ("ProdNumber")
    REFERENCES public.products ("ProdNumber") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT "Category" FOREIGN KEY ("Category")
    REFERENCES public.productcategory ("CategoryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;